ALTER TABLE shops ADD COLUMN is_featured INTEGER NOT NULL DEFAULT 0;
ALTER TABLE shops ADD COLUMN show_on_map INTEGER NOT NULL DEFAULT 1;
ALTER TABLE shops ADD COLUMN is_verified INTEGER NOT NULL DEFAULT 1;
ALTER TABLE shops ADD COLUMN order_num INTEGER NOT NULL DEFAULT 1;
